dist: trusty
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "dantealighieri1265"
    token: "4b126026a92699b1557128521dd18be757366aa7"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify -P coverage sonar:sonar
